workflows:
  release-workflow:
    triggering:
      events:
        - tag
      tag_patterns:          
        - pattern: release-*
      cancel_previous_builds: true
    environment:
      groups:
        - app_store_credentials
        - plists
      vars:
        XCODE_WORKSPACE: "DailyAthkar.xcworkspace"
        XCODE_SCHEME: "DailyAthkar"
      cocoapods: 1.13.0
      xcode: 14.1
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
      - name: Fetch signing files
        script: |
                    app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
                    keychain add-certificates 
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Setup Info PList files
        script: |
                    echo $IOS_FIREBASE_SECRET > DailyAthkar/GoogleService-Info.plist
                    echo $IOS_TOKENS > DailyAthkar/tokens.plist
      - name: Increment build number
        script: |
                  LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number '821664774')
                  NEXT_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
                  echo "LATEST_BUILD_NUMBER $LATEST_BUILD_NUMBER"
                  echo "NEXT_BUILD_NUMBER $NEXT_BUILD_NUMBER"
                  agvtool new-version -all $NEXT_BUILD_NUMBER
      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # Contents of the API key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Alphanumeric value that identifies the API key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Alphanumeric value that identifies who created the API key
        submit_to_testflight: false        # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.
      # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
      #     - group name 1
      #     - group name 2
 